


*** Variables ***
#URL
${url_production_admin}       http://qlttltcl.atwebpages.com/admin
${url_local_admin}        http://localhost/Project/tschool/admin
${url_local_page}        http://localhost/Project/tschool
${url_production_page}       http://qlttltcl.atwebpages.com
${base_url}     http://localhost/Project/tschool/api
${base_production_url}     http://qlttltcl.atwebpages.com/api

#Browser
${browser}    Chrome

#Locator
${locator_username}    //input[@name='admin_account']
${locator_password}     //input[@name="admin_password"]
${locator_button}       //button[@id='button_login']

#Data
${text_256_character}       Tired of scrolling through the same courses? when you create an account you’ll always come back to where you left off. With an account you can also be notified of new replies, save bookmarks, and use likes to thank others. We can all work together to make th
${text_256_character_email}       tdddddddddddddddddddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdhhhhhhhhhhhhhdddddddddđhhhhhhhhhhhh@gmail.com
${data_username}    Sally51
${data_password}    123456

#Link
${image}    C:\\Users\\nguye\\PycharmProjects\\DATN_RF\\Upload









